[phases.setup]
nixPkgs = [
  "php82",
  "php82Extensions.pdo_pgsql",
  "php82Extensions.mbstring",
  "php82Extensions.xml",
  "php82Extensions.tokenizer",
  "php82Extensions.ctype",
  "php82Extensions.fileinfo",
  "php82Extensions.openssl",
  "php82Extensions.bcmath",
  "php82Extensions.curl",
  "php82Extensions.zip",
  "php82Packages.composer",
  "nodejs_20",
  "nodePackages.npm"
]
